### ISSUE TITLE
Advanced Port Mapping

### ISSUE THREAD

**Issue by mananchawla2005** [replit/polygott#187]
Hey first of all thankyou folks working at repl.it for providing such a great product. Absolutely love it. I had one request in my mind. Can you please have advanced port mapping like for example right now every opened port gets proxied to port 80 of the url. Can it be something like we can have multiple ports opened running multiple servers. So for example server 1 can be on example.repl.com:9000 and other on example.repl.com:7000 . Thanks once again. Hope to get a reply soon.

**Comment by lhchavez** [comment]
Stay tuned at the blog (but can't give a hard ETA)!

Closing this since that's not a Polygott issue.
