### ISSUE TITLE
AttributeError: module 're' has no attribute 'Match'

### ISSUE THREAD

**Issue by frissyn** [replit/polygott#231]
**Issue:**

Running `make` command in root directory with any arguments fails with a Python `AttributeError`.

**Environment:**

Bash REPL on [`replit.com`](https://replit.com/new/bash). Cloned `polygott` repo into base directory.

**Error:**
```py
Traceback (most recent call last):
  File "./extra/manifest_tool.py", line 465, in <module>
    _main()
  File "./extra/manifest_tool.py", line 459, in _main
    context(args)
  File "./extra/manifest_tool.py", line 333, in context
    def _sub_globs(match: re.Match) -> str:
AttributeError: module 're' has no attribute 'Match'
Makefile:30: recipe for target 'build/context.tar.bz2' failed
make: *** [build/context.tar.bz2] Error 1
```

**Comment by lhchavez** [comment]
what version do you have in your system? you might need 3.8+

**Comment by frissyn** [comment]
Well I'm in a Bash Repl, and the Python version is listed as `3.8.8`. If it's any consolation, I was able to fix the error by changing `./extra/manifest_tool.py` to `python3 extra/manifest_tool.py` in the Makefile.

**Comment by lhchavez** [comment]
ah that's because `/usr/bin/python3` is 3.6.9 and `python3` (which is picked up from `/opt/virtualenvs/python3/bin/python3`) is 3.8.8.

we may need to use `#!/usr/bin/env python3` as the shebang for that file to fix that.
