### ISSUE TITLE
Support for .NET Core runtime vs Mono

### ISSUE THREAD

**Issue by tmarkovski** [replit/polygott#261]
Adding support for .NET core SDK is fairly straightforward. Using the `dotnet` CLI allows modern project management and runtime. Currently, replit supports only `mono` runtime, which allows only compiling a file into an exe output.
Being able to use packages with C# is a basic requirement.
While it's also [fairly straightforward](https://replit.com/@trinsic/VaccinationSampleNet#run.sh) to install `dotnet` separately, I believe this should be a core supported feature.

**Comment by lhchavez** [comment]
We are slowly moving away from polygott in favor of nix: https://blog.replit.com/nix

I believe @ALANVF has a few templates with dotnet that may already be usable.

**Comment by tmarkovski** [comment]
Wonderful! All I needed. Thank you
