### ISSUE TITLE
Upgrade Go

### ISSUE THREAD

**Issue by 89z** [replit/polygott#279]
I just got this error:

~~~
undefined: io.ReadAll
note: module requires Go 1.17
exit status 2
~~~

Looks like the problem is here:

https://github.com/replit/polygott/blob/9180d8b24b181125577e98a8f5418781e863e852/languages/go.toml#L13-L16

**Comment by cbrewster** [comment]
Hi @89z, here is a repl with Go 1.17 configured: https://replit.com/@ConnorBrewster/Go117#replit.nix

We are transitioning from Polygott to Nix, check out https://blog.replit.com/nix for more information.

**Comment by 89z** [comment]
I dont understand, I am trying to run a server here:

https://replit.com/@89z

I dont need a REPL.
