### ISSUE TITLE
typo in nextjs.toms

### ISSUE THREAD

**Issue by kjk** [replit/polygott#60]
In https://github.com/replit/polygott/blob/master/languages/nextjs.toml#L9:

```setup = [
  "npm install -g prettier@1.13.4",
  "mkdir -p /hom/runner/pages",
  "yarn install"
]
```

Pretty sure it was meant to be: ` "mkdir -p /home/runner/pages",` (`hom/` => `home/`).

**Comment by isuckatprogram** [comment]
Pull Request: https://github.com/replit/polygott/pull/115
