### ISSUE TITLE
add deno.land

### ISSUE THREAD

**Issue by rafaelcastrocouto** [replit/polygott#62]
https://deno.land/ is the new node.js (https://www.youtube.com/watch?v=puXyo1jGQys)
It already works with the current structure https://repl.it/@rafaelcastrocouto/deno-repl-tests
It would be very nice to have it in the languages list
I could work on this with a little help!

**Comment by turbio** [comment]
that sounds great! we'd love to add support for deno

**Comment by lunaroyster** [comment]
Here we go @rafaelcastrocouto! https://repl.it/languages/deno

**Comment by rafaelcastrocouto** [comment]
Awesome! How long til it shows up in front-end languages list?

**Comment by rafaelcastrocouto** [comment]
It is online! Great job!
